stages:
  - build

build:
  stage: build
  image:
    name: rust:latest
  script:
    - apt-get update
    - apt-get install -y cmake g++ git clang
    - git clone https://github.com/scipopt/soplex.git
    - cd soplex
    - git checkout bugfix-60
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - cd ../..

    - mkdir build
    - cd build
    - cmake .. -DAUTOBUILD=ON -DSOPLEX_DIR=soplex/build -DCMAKE_INSTALL_PREFIX=../install
    - make -j
    - make install
    - cd ..

    - git clone https://github.com/scipopt/russcip.git
    - cd russcip
    - LD_LIBRARY_PATH=$CI_PROJECT_DIR/install/lib SCIPOPTDIR=$CI_PROJECT_DIR/install cargo test --release
