stages:
  - build

build:
  stage: build
  image:
    name: rust:latest
  script:
    - apt-get update
    - apt-get install -y cmake g++ git
    - git clone https://github.com/scipopt/soplex.git
    - cd soplex
    - git checkout bugfix-60
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    - cd ../..

    - mkdir build
    - cd build
    - cmake .. -DAUTOBUILD=ON -DSOPLEX_DIR=soplex/build
    - make -j
    - cd ..

    - git clone https://github.com/scipopt/russcip.git
    - cd russcip
    - SCIPOPTDIR=../build cargo test --release
