name: Build Binaries


# on:
#   push:
#     tags:
#       - v** # TODO: add regex for version numbers

on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false # do not stop all builds if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2.2.0
    - run: echo ${{ env.CONDA_PREFIX }}

    # - name: Install dependencies
    #   run: |
    #     conda install -c conda-forge scip
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: libscip
    #     path: ${{ env.CONDA_PREFIX }}/lib

    
    
        
        

      

        


